---
# install_rke2/tasks/binary.yml

#
# Download and install the binary
#

# This is the original command used by the install script:
# curl -w "%{url_effective}" -L -s -S "${version_url}" -o /dev/null | sed -e 's|.*/||'
#
# with version_url being defined as "${INSTALL_RKE2_CHANNEL_URL}/${INSTALL_RKE2_CHANNEL}"

- name: 'Detect latest kubernetes version, unless specified by the user'
  uri:
    url: "{{ rke2_installation_url }}/{{ rke2_installation_channel }}"
  delegate_to: 'localhost'
  become: 'false'
  changed_when: 'false'
  check_mode: 'false'
  register: get_rke2_version
  when:
    - 'rke2_version is undefined'

- set_fact:
    rke2_version: "{{ get_rke2_version.url | basename }}"
  when:
    - 'rke2_version is undefined'

- name: 'Download rke2 binary'
  get_url:
    url: "https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/{{ rke2_binary_download_name }}"
    dest: "{{ path_to_install_to }}/rke2"
    checksum: "sha256:https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/{{ rke2_sha256sum_download_name }}"
    owner: 'root'
    group: 'root'
    mode: '0755'
  register: download_binary
  notify:
    - 'Restart the rke2 service'

- name: 'Set fact to ignore errors in check mode, if binary would be downloaded'
  set_fact:
    ignore_errors_when_binary_downloaded: 'true'
  when:
    - 'download_binary.changed | bool'
    - 'ansible_check_mode | bool'

- name: 'Create necessary links to binary'
  ansible.builtin.file:
    # links are relative, not absolute, so only giving 'rke2' as source here is intended...
    src: 'rke2'
    dest: "{{ path_to_install_to }}/{{ item }}"
    state: 'link'
    owner: 'root'
    group: 'root'
  loop:
    - 'ctr'
    - 'crictl'
    - 'kubectl'
  ignore_errors: "{{ ignore_errors_when_binary_downloaded }}"
