---
# install_rke2/tasks/kubeconfig.yml

#
# kubeconfig
#

- name: 'Check if we already have a rke2-kubeconfig file'
  ansible.builtin.stat:
    path: 'rke2-kubeconfig'
  delegate_to: 'localhost'
  become: 'false'
  register: does_rke2_kubeconfig_exist

- name: 'Fetch kubeconfig to Ansible control node'
  ansible.builtin.fetch:
    src: '/etc/rancher/rke2/rke2.yaml'
    dest: 'rke2-kubeconfig'
    flat: 'yes'
  when:
    - 'not does_rke2_kubeconfig_exist.stat.exists | bool'

- name: 'Check if we now have a rke2-kubeconfig file'
  ansible.builtin.stat:
    path: 'rke2-kubeconfig'
  delegate_to: 'localhost'
  become: 'false'
  register: does_rke2_kubeconfig_exist_now

- name: 'Fix permissions on rke2-kubeconfig'
  ansible.builtin.file:
    path: 'rke2-kubeconfig'
    mode: '0600'
  delegate_to: 'localhost'
  become: 'false'
  when:
    - 'does_rke2_kubeconfig_exist_now.stat.exists | bool'

- name: 'Change server IP in kubeconfig file to external_ip (or the default IPv4 address)'
  ansible.builtin.lineinfile:
    path: 'rke2-kubeconfig'
    regexp: '(\s*)server: https://127.0.0.1:(.*)'
    line: '\1server: https://{{ external_ip | default(hostvars[inventory_hostname]["ansible_default_ipv4"]["address"] )}}:\2'
    backrefs: 'true'
  delegate_to: 'localhost'
  become: 'false'
  ignore_errors: "{{ ansible_check_mode }}"
