---
# install_rke2/tasks/main.yml

- name: 'Run set_facts.yml'
  ansible.builtin.include_tasks: 'set_facts.yml'

- name: 'Run binary.yml'
  ansible.builtin.include_tasks: 'binary.yml'
  when:
    - not install_via_rpm | bool

- name: 'Run rpm_installation.yml'
  ansible.builtin.include_tasks: 'rpm_installation.yml'
  when:
    - install_via_rpm | bool

- name: 'Run configuration.yml'
  ansible.builtin.include_tasks: 'configuration.yml'

- name: 'Run scripts.yml'
  ansible.builtin.include_tasks: 'scripts.yml'
  when:
    - not install_via_rpm | bool

- name: 'Run service.yml'
  ansible.builtin.include_tasks: 'service.yml'
  when:
    - not install_via_rpm | bool

#
# Start and enable the service
#

- name: 'Start and enable the service'
  ansible.builtin.service:
    name: "rke2-{{ rke2_node_type }}.service"
    state: 'started'
    enabled: true

- name: 'Run kubeconfig.yml'
  ansible.builtin.include_tasks: 'kubeconfig.yml'
  when: 'rke2_node_type == "server"'

- name: 'Run token.yml'
  ansible.builtin.include_tasks: 'token.yml'
  when:
    - 'rke2_node_type == "server"'
    - 'fetch_token | bool'
