---
# install_rke2/tasks/scripts.yml

#
# Scripts
#

- name: 'Create the uninstall script'
  template:
    src: 'rke2-uninstall.sh.j2'
    dest: "{{ path_to_install_to }}/bin/rke2-uninstall.sh"
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Create the killall script'
  template:
    src: 'rke2-killall.sh.j2'
    dest: '{{ path_to_install_to }}/bin/rke2-killall.sh'
    owner: 'root'
    group: 'root'
    mode: '0755'
