---
# install_rke2/tasks/service.yml

#
# Create the env and service files
#

- name: 'Create directories'
  file:
    path: "{{ systemd_directory_path }}"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify:
    - 'Trigger systemctl daemon-reload'
    - 'Restart the rke2 service'

- name: "Create the env file rke2-{{ rke2_node_type }}.env"
  template:
    src: "rke2-{{ rke2_node_type }}.env.j2"
    dest: "{{ systemd_directory_path }}/rke2-{{ rke2_node_type }}.env"
    owner: 'root'
    group: 'root'
    mode: '0640'
  notify:
    - 'Trigger systemctl daemon-reload'
    - 'Restart the rke2 service'

- name: "Create systemd service file rke2-{{ rke2_node_type }}.service"
  template:
    src: 'rke2-{{ rke2_node_type }}.service.j2'
    dest: "{{ systemd_directory_path }}/rke2-{{ rke2_node_type }}.service"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Trigger systemctl daemon-reload'
    - 'Restart the rke2 service'

#
# Start and enable the service
#

- name: 'Make sure systemd is aware of all newly created files'
  meta: flush_handlers

- name: 'Start and enable the service'
  service:
    name: "rke2-{{ rke2_node_type }}.service"
    state: 'started'
    enabled: 'true'
