---
# install_rke2/tasks/token.yml

#
# token
#
- name: 'Fetch token to Ansible control node'
  ansible.builtin.fetch:
    src: "{{ data_dir | default('/var/lib/rancher/rke2') }}/server/node-token"
    dest: 'rke2-token'
    mode: '0600'
    flat: 'yes'
